name: heac-0.2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - xgboost
  - lightgbm
  - joblib
  - pip
  - pip:
    - pymatgen
    - mp-api
    - emmet-core
    - matminer
    - streamlit
    - catboost
    - optuna
    - shap
    - python-dotenv
